name: adding file
on:
  push:
  public:
jobs:
 scan:
   runs-on: ubuntu-latest
   steps:
     - name: test file
       run: |
           dotnet nuget add source --username "vinothkumarGanesan" --password "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"  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/vinothkumarGanesan/index.json"
           dir $GITHUB_WORKSPACE/AddGitHubAction.1.0.0/lib/netcoreapp3.1
           dotnet $GITHUB_WORKSPACE/AddGitHubAction.1.0.0/lib/netcoreapp3.1/AddGitHubAction.dll "TestingGitVinoth" "vinothkumarGanesan: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"
